### ISSUE TITLE
dhcpcd-10.2.2 build issue

### ISSUE THREAD

**Issue by dharanlinux** [NetworkConfiguration/dhcpcd#493]
Hi Team,

I am trying to build the dhcpcd-10.2.2 with kernel-3.12 and facing below issue.

```
if-linux.c: In function 'if_route':
if-linux.c:1777:38: error: 'RTA_EXPIRES' undeclared (first use in this function)
   add_attr_32(&nlm.hdr, sizeof(nlm), RTA_EXPIRES, expires);
                                      ^
if-linux.c:1777:38: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by rsmarples** [comment]
> Is there any particular reason for building against such an old Linux kernel?

dhcpcd still works on 2.6 kernels I believe. Not that I have one to hand right now!

Older kernels are generally a lot smaller in terms of on disk size and memory usage and thus favoured in old small embedded devices.
